// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {view} from '../models';

export function Add(arg1:string,arg2:string,arg3:string):Promise<view.ContactResult>;

export function CopyPublicKey(arg1:string):Promise<view.VoidResult>;

export function Delete(arg1:string):Promise<view.VoidResult>;

export function ImportFromFile(arg1:string,arg2:string):Promise<view.ContactResult>;

export function List():Promise<view.ContactsResult>;

export function Rename(arg1:string,arg2:string,arg3:string):Promise<view.ContactResult>;
