// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2, arg3) {
  return window['go']['view']['Contacts']['Add'](arg1, arg2, arg3);
}

export function CopyPublicKey(arg1) {
  return window['go']['view']['Contacts']['CopyPublicKey'](arg1);
}

export function Delete(arg1) {
  return window['go']['view']['Contacts']['Delete'](arg1);
}

export function ImportFromFile(arg1, arg2) {
  return window['go']['view']['Contacts']['ImportFromFile'](arg1, arg2);
}

export function List() {
  return window['go']['view']['Contacts']['List']();
}

export function Rename(arg1, arg2, arg3) {
  return window['go']['view']['Contacts']['Rename'](arg1, arg2, arg3);
}
