// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BaseName(arg1) {
  return window['go']['view']['Crypto']['BaseName'](arg1);
}

export function Cancel(arg1) {
  return window['go']['view']['Crypto']['Cancel'](arg1);
}

export function ChooseSavePath(arg1, arg2) {
  return window['go']['view']['Crypto']['ChooseSavePath'](arg1, arg2);
}

export function Decrypt(arg1, arg2, arg3) {
  return window['go']['view']['Crypto']['Decrypt'](arg1, arg2, arg3);
}

export function DecryptWithPassphrase(arg1, arg2, arg3, arg4) {
  return window['go']['view']['Crypto']['DecryptWithPassphrase'](arg1, arg2, arg3, arg4);
}

export function Encrypt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['view']['Crypto']['Encrypt'](arg1, arg2, arg3, arg4, arg5);
}

export function EncryptWithPassphrase(arg1, arg2, arg3, arg4) {
  return window['go']['view']['Crypto']['EncryptWithPassphrase'](arg1, arg2, arg3, arg4);
}

export function Inspect(arg1) {
  return window['go']['view']['Crypto']['Inspect'](arg1);
}

export function PickFiles(arg1) {
  return window['go']['view']['Crypto']['PickFiles'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['view']['Crypto']['ShowInFolder'](arg1);
}

export function SuggestDecryptOutput(arg1) {
  return window['go']['view']['Crypto']['SuggestDecryptOutput'](arg1);
}

export function SuggestEncryptOutput(arg1) {
  return window['go']['view']['Crypto']['SuggestEncryptOutput'](arg1);
}
