// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {view} from '../models';

export function BaseName(arg1:string):Promise<view.StringResult>;

export function Cancel(arg1:string):Promise<view.VoidResult>;

export function ChooseSavePath(arg1:string,arg2:string):Promise<view.StringResult>;

export function Decrypt(arg1:string,arg2:string,arg3:string):Promise<view.StringResult>;

export function DecryptWithPassphrase(arg1:string,arg2:string,arg3:string,arg4:string):Promise<view.StringResult>;

export function Encrypt(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<view.StringResult>;

export function EncryptWithPassphrase(arg1:string,arg2:string,arg3:string,arg4:string):Promise<view.StringResult>;

export function Inspect(arg1:string):Promise<view.FileKindResult>;

export function PickFiles(arg1:string):Promise<view.PathsResult>;

export function SuggestDecryptOutput(arg1:string):Promise<view.StringResult>;

export function SuggestEncryptOutput(arg1:string):Promise<view.StringResult>;
