// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {view} from '../models';

export function Create(arg1:string,arg2:Array<string>):Promise<view.GroupResult>;

export function Delete(arg1:string):Promise<view.VoidResult>;

export function List():Promise<view.GroupsResult>;

export function Update(arg1:string,arg2:string,arg3:Array<string>):Promise<view.GroupResult>;
