// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['view']['Groups']['Create'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['view']['Groups']['Delete'](arg1);
}

export function List() {
  return window['go']['view']['Groups']['List']();
}

export function Update(arg1, arg2, arg3) {
  return window['go']['view']['Groups']['Update'](arg1, arg2, arg3);
}
