// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup() {
  return window['go']['view']['Keys']['Backup']();
}

export function CopyPublicKey() {
  return window['go']['view']['Keys']['CopyPublicKey']();
}

export function ExportPublicKey() {
  return window['go']['view']['Keys']['ExportPublicKey']();
}

export function Generate(arg1) {
  return window['go']['view']['Keys']['Generate'](arg1);
}

export function Lock() {
  return window['go']['view']['Keys']['Lock']();
}

export function Restore(arg1) {
  return window['go']['view']['Keys']['Restore'](arg1);
}

export function Status() {
  return window['go']['view']['Keys']['Status']();
}

export function Touch() {
  return window['go']['view']['Keys']['Touch']();
}

export function Unlock(arg1) {
  return window['go']['view']['Keys']['Unlock'](arg1);
}
