// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {view} from '../models';

export function Backup():Promise<view.StringResult>;

export function CopyPublicKey():Promise<view.VoidResult>;

export function ExportPublicKey():Promise<view.StringResult>;

export function Generate(arg1:string):Promise<view.KeyStatusResult>;

export function Lock():Promise<view.KeyStatusResult>;

export function Restore(arg1:string):Promise<view.KeyStatusResult>;

export function Status():Promise<view.KeyStatusResult>;

export function Touch():Promise<void>;

export function Unlock(arg1:string):Promise<view.KeyStatusResult>;
