// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {view} from '../models';

export function ChooseDir(arg1:string,arg2:string):Promise<view.StringResult>;

export function Get():Promise<view.SettingsResult>;

export function SetAutoLock(arg1:number):Promise<view.SettingsResult>;

export function SetDecryptDir(arg1:string):Promise<view.SettingsResult>;

export function SetEncryptDir(arg1:string):Promise<view.SettingsResult>;

export function SetTheme(arg1:string):Promise<view.SettingsResult>;
