// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDir(arg1, arg2) {
  return window['go']['view']['Settings']['ChooseDir'](arg1, arg2);
}

export function Get() {
  return window['go']['view']['Settings']['Get']();
}

export function SetAutoLock(arg1) {
  return window['go']['view']['Settings']['SetAutoLock'](arg1);
}

export function SetDecryptDir(arg1) {
  return window['go']['view']['Settings']['SetDecryptDir'](arg1);
}

export function SetEncryptDir(arg1) {
  return window['go']['view']['Settings']['SetEncryptDir'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['view']['Settings']['SetTheme'](arg1);
}
