// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {view} from '../models';

export function Get():Promise<view.SettingsResult>;

export function SetAutoLock(arg1:number):Promise<view.SettingsResult>;
