#!/usr/bin/env bash
# Regenerates THIRD_PARTY_LICENSES.md from the modules actually linked into the
# binary.
#
# This is not paperwork. Age GUI is GPLv3, but its dependencies are BSD, MIT and
# Apache-2.0, and all three require that *binary* distributions reproduce their
# copyright notices. Shipping a .deb or an installer without them is a licence
# violation, so this file has to travel inside every package.
#
# Generated rather than hand-written so it cannot quietly drift out of date the
# next time a dependency is added. CI re-runs it and fails if the committed copy
# differs.
#
#     ./scripts/gen-third-party-licenses.sh > THIRD_PARTY_LICENSES.md
set -euo pipefail

cd "$(dirname "$0")/.."
MODCACHE="$(go env GOMODCACHE)"

# The production tags matter: without them `go list` walks the stub build and
# misses the GTK/WebKit frontend's dependencies entirely.
mapfile -t MODULES < <(
    go list -deps -tags production,webkit2_41 \
        -f '{{if not .Standard}}{{.Module.Path}}@{{.Module.Version}}{{end}}' . 2>/dev/null |
        sort -u | grep -v '^dawidroszman' | grep -v '^$'
)

cat <<'HEADER'
# Third-party licenses

Age GUI is licensed under the GNU General Public License v3.0 or later; see
[LICENSE](LICENSE).

It builds on the work below. Each of these is distributed under a permissive
licence that is compatible with the GPL, and each requires its copyright notice
to be reproduced in binary distributions — which is what this file is for. Their
own terms, reproduced in full, continue to govern their code.

This file is generated by `scripts/gen-third-party-licenses.sh`. Do not edit it
by hand.

HEADER

echo "## Summary"
echo
echo "| Component | Version | License |"
echo "|---|---|---|"

declare -A LICENSE_PATH
for mod in "${MODULES[@]}"; do
    path="${mod%@*}"
    version="${mod##*@}"
    dir="$MODCACHE/$mod"

    lic="$(find "$dir" -maxdepth 1 \( -iname 'LICENSE*' -o -iname 'COPYING*' \) 2>/dev/null | head -1)"
    if [ -z "$lic" ]; then
        echo "error: no licence file found for $mod" >&2
        exit 1
    fi
    LICENSE_PATH["$mod"]="$lic"

    # Identify by the licence's own distinctive wording rather than trusting a
    # metadata field that nothing verifies.
    if grep -qi "Apache License" "$lic"; then
        kind="Apache-2.0"
    elif grep -qi "All advertising materials" "$lic"; then
        # Called out explicitly: BSD-4-Clause is GPL-incompatible and would make
        # the whole project undistributable. Fail loudly rather than paper over it.
        echo "error: $mod is BSD-4-Clause, which is incompatible with the GPL" >&2
        exit 1
    elif grep -qi "endorse or promote products derived" "$lic"; then
        kind="BSD-3-Clause"
    elif grep -qi "Redistribution and use in source and binary forms" "$lic"; then
        kind="BSD-2-Clause"
    elif grep -qi "Permission is hereby granted, free of charge" "$lic"; then
        kind="MIT"
    else
        echo "error: could not identify the licence of $mod ($lic)" >&2
        exit 1
    fi

    echo "| \`$path\` | $version | $kind |"
done

echo "| Svelte (bundled runtime) | see frontend/package.json | MIT |"
echo

cat <<'FRONTEND'
The compiled frontend embeds the Svelte runtime (MIT). Everything else under
`frontend/node_modules` is build-time tooling and is not distributed.

FRONTEND

echo "## Full license texts"
echo

for mod in "${MODULES[@]}"; do
    echo "### ${mod%@*}"
    echo
    echo '```'
    cat "${LICENSE_PATH[$mod]}"
    echo '```'
    echo
done
